name: Packagist Update

on:
  push:
    tags:
      - '*'

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update Packagist
        run: |
          echo "Updating Packagist for repository: https://github.com/agabaandre/exchange_email_service"
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"repository":{"url":"https://github.com/agabaandre/exchange_email_service"}}' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}"
          echo "Packagist update request sent successfully"
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
