name: Update Packagist

on:
  push:
    tags:
      - '*'

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packagist
        uses: docker://triggerpackagist:latest
        with:
          args: 'https://packagist.org/api/update-package?username=YOUR_PACKAGIST_USERNAME&apiToken=YOUR_PACKAGIST_TOKEN&repository=https://github.com/agabaandre/exchange_email_service'
