name: Update Packagist

on:
  push:
    tags:
      - '*'

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Update Packagist
        uses: packagist/action@v1
        with:
          packagist-username: ${{ secrets.PACKAGIST_USERNAME }}
          packagist-token: ${{ secrets.PACKAGIST_TOKEN }}
          packagist-repository-url: https://github.com/agabaandre/exchange_email_service
